baseURL = "https://www.example.com"
languageCode = "fi-FI"
title = "Porkkanala"
theme = "hugo-digital-garden-theme"
themesdir = "themes"
copyright = "Alpi ©"


[params]
  name = "Porkkanala"
  description = "Reseptejä porkkanalla ja ilman"
  initials = "Porkkanala"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "#"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "#"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "#"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Reseptit"
    url = "/reseptit/"
    weight = 1
  [[menu.main]]
    name = "Filosofia"
    url = "/filosofia/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3 
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'